### ISSUE TITLE
Does not save zip file

### ISSUE THREAD

**Issue by thundergreen** [adizanni/ExportToHASS#1] opened 2021-07-04 16:17 UTC
I succesfully installed the plugin and it is well showing under tools --> export ... but the zip file will never be exported. I already restarte Sweet home 3d

**Comment by adizanni** [comment] 2021-07-04 16:41
Hello Thundergreen, as I already told to others, I'm moving in an uncharted territory with this plugin. I'm not a Java developer and plugin working depends on many external factors. So please be patient. Try to run Sweethome from the cmd line first (cmd in windows, terminal in Linux). If the zip is not generarated it means there is an error. The stack trace of the error will appear in the cmd console. Please copy paste here the stack trace. If there is no stack trace I suggest to send me your model via file share. I'm going to be off a few days but when back I will fix the issue. The problem is that I discover every  day new model object types that have to be managed for the export to work well. This morning I have released a patch to manage Levels....

**Comment by jesserockz** [comment] 2021-07-05 05:29
Here you go:

As soon as I hit the `save` button it closes the dialog and nothing else happens.

Arch Linux 
Sweet home 3D 6.5
OpenJDK version 16.0.1

```log
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "com.eteks.sweethome3d.model.Content.openStream()" because "<parameter1>" is null
	at com.eteks.sweethome3d.tools.TemporaryURLContent.copyToTemporaryURLContent(Unknown Source)
	at com.eteks.sweethome3d.j3d.ModelManager.loadModel(Unknown Source)
	at com.eteks.sweethome3d.j3d.ModelManager.loadModel(Unknown Source)
	at com.eteks.sweethome3d.j3d.HomePieceOfFurniture3D.loadPieceOfFurnitureModel(Unknown Source)
	at com.eteks.sweethome3d.j3d.HomePieceOfFurniture3D.createPieceOfFurnitureNode(Unknown Source)
	at com.eteks.sweethome3d.j3d.HomePieceOfFurniture3D.<init>(Unknown Source)
	at com.eteks.sweethome3d.j3d.Object3DBranchFactory.createObject3D(Unknown Source)
	at com.eteks.sweethome3d.plugin.exporthass.ExportHass$ExportHassAction.exportHomeStructure(ExportHass.java:145)
	at com.eteks.sweethome3d.plugin.exporthass.ExportHass$ExportHassAction.execute(ExportHass.java:103)
	at com.eteks.sweethome3d.swing.HomePane$ActionAdapter.actionPerformed(Unknown Source)
	at com.eteks.sweethome3d.swing.ResourceAction$AbstractDecoratedAction.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adizanni** [comment] 2021-07-10 09:44
I think there is something wrong with the permission to write in the temporary folder. If you are running in windows (and you trust my plugin...) try to run the sweethome3d application with Administrator rights (right click on the application icon and click on 'Run as administrator') and let me know

**Comment by firstchair** [comment] 2021-07-21 10:19
At first, great that you're creating this! Are there logs saved somewhere during the export?

**Comment by adizanni** [comment] 2021-07-21 21:24
No not yet, I will do a release this week-end to be sure I can have better troubleshooting. Of course to share your sh3d model file with the faulty objects can help. There are a lot of object types I'm not yet mqnqging and they may cause unhandled exceptions. Please be patient.....

**Comment by adizanni** [comment] 2021-07-24 18:16
I think it would help to send me the sh3d file with the objects that were causing errors, there are so many cases and I have to manage them all for the export to work fine, the more I have examples the more the plugin will be stable

**Comment by squirrel289** [comment] 2021-08-19 22:16
> Here you go:
> 
> As soon as I hit the `save` button it closes the dialog and nothing else happens.
> 
> Arch Linux
> Sweet home 3D 6.5
> OpenJDK version 16.0.1
> 
> ```
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "com.eteks.sweethome3d.model.Content.openStream()" because "<parameter1>" is null
> 	at com.eteks.sweethome3d.tools.TemporaryURLContent.copyToTemporaryURLContent(Unknown Source)
> 	at com.eteks.sweethome3d.j3d.ModelManager.loadModel(Unknown Source)
> 	at com.eteks.sweethome3d.j3d.ModelManager.loadModel(Unknown Source)
> 	at com.eteks.sweethome3d.j3d.HomePieceOfFurniture3D.loadPieceOfFurnitureModel(Unknown Source)
> 	at com.eteks.sweethome3d.j3d.HomePieceOfFurniture3D.createPieceOfFurnitureNode(Unknown Source)
> 	at com.eteks.sweethome3d.j3d.HomePieceOfFurniture3D.<init>(Unknown Source)
> 	at com.eteks.sweethome3d.j3d.Object3DBranchFactory.createObject3D(Unknown Source)
> 	at com.eteks.sweethome3d.plugin.exporthass.ExportHass$ExportHassAction.exportHomeStructure(ExportHass.java:145)
> 	at com.eteks.sweethome3d.plugin.exporthass.ExportHass$ExportHassAction.execute(ExportHass.java:103)
> 	at com.eteks.sweethome3d.swing.HomePane$ActionAdapter.actionPerformed(Unknown Source)
> 	at com.eteks.sweethome3d.swing.ResourceAction$AbstractDecoratedAction.actionPerformed(Unknown Source)
> 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
> 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
> 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
> 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
> 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
> 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
> 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> ```

Receiving identical issue in a very different operating environment:
macOS 11.1
SweetHome3D 6.6a
Oracle Java 1.8.0_291

**Comment by uspass** [comment] 2021-08-20 05:27
That's because your sh3d has 2 levels. The plugin can't do that. If you delete Level 1, it exports OK.

cheers,
us

**Comment by adizanni** [comment] 2021-08-20 09:15
Hello thanks uss.

Squirrel, I confirm, today I'm not supporting multiple level in the plugin. This may change in the future even though, the rendering of multiple floors is not really good for the card, it works better on single floors.

**Comment by squirrel289** [comment] 2021-08-20 15:16
Thank you for the info, that's helpful to know.  Given that, I tried deleting the second level and still received the same error so I tried exporting new model using the 4BR demo house and still see the same.

I've attached the demo house for reference.
[Test.sh3d.zip](https://github.com/adizanni/ExportToHASS/files/7022502/Test.sh3d.zip)

**Comment by chrisvor** [comment] 2021-08-22 13:09
Hi. I also have a SH3D file containing two floors with multiple layers on each (some on same elevation, just to have lights and doors separately from the main house plan. Following this issue, I have copied all the objects on the ground floor into a new SH3D file that only has one layer, and used your tool to create the ZIP. All worked fine. However, when I repeated the same thing for the first floor, into a new SH3D file, the tool does not produce the ZIP file. Using windows 10. I tried starting the application from the command line, but I dont get any error log output

**Comment by adizanni** [comment] 2021-08-22 13:45
Hello all, I'm able to reproduce the issue in Windows 10 but the linux version is working. 
I'm going to need a little time as debugging for windows ain't easy.

**Comment by chrisvor** [comment] 2021-08-22 18:39
> Hello all, I'm able to reproduce the issue in Windows 10 but the linux version is working.
> I'm going to need a little time as debugging for windows ain't easy.

Great! Thank you for your great work!

**Comment by adizanni** [comment] 2021-08-24 20:53
Hello all, I'm back now, in fact my previous post is not correct. The plugin was not working because I was using a previous version. Instead of following my procedure in the readme (I will modify it) please follow these steps in windows:

1. Close sweethome3d application
2. Download the latest version of the plugin [here](https://github.com/adizanni/ExportToHASS/raw/main/dist/ExportToHassPlugin.sh3p)
3. Open the folder located here: C:\Users\<your user name>\AppData\Roaming\eTeks\Sweet Home 3D\plugins (replace <your user name> with your actual user name
4. Copy the file downloaded in step 2 to the folder identified in step 3
5. Restart sweethome3d,  

In this release I have added a final message box to show that the export was succesful. If you do not see the message box it means you have other problems. But now it will be more difficult for me to debug (until I will put some logs, but this plugin is really developed in best effort). Please try!!!

**Comment by squirrel289** [comment] 2021-08-24 20:57
Is there an equivalent change on directions on MacOS 11.1?

**Comment by adizanni** [comment] 2021-08-24 21:13
I cannot test in MacOS but, as far as I know, it is really similar to Linux. Try to search for the file name ExportToHassPlugin.sh3p. In Linux this is located in /home/username/.eteks/sweethome3d/plugin. I have the impression that the double-click on the plugin file is not always working in windows (I cannot tell in MacOS and in Linux it has never worked so you need to copy the file manually).

**Comment by adizanni** [comment] 2021-08-24 21:16
Wait a moment, your sh3d model is not working in my linux either. It may be a grouped object causing an exception. Try to start with a simple model and see if it is working,.....

**Comment by ahd71** [comment] 2021-08-25 12:57
I can confirm that I can export a model until i group two objects, then it is not possible anymore. I use groups a lot for organization so would be great when this would be handled, and as others have said, I really appreciate the time you have put into this. keep up the good work!

**Comment by chrisvor** [comment] 2021-08-25 14:21
Yes I just noticed that my "first floor" had a groupped object and it was not exporting. As soon as I ungrouped them, the export succeeded. So it's definitely an issue with the groups

**Comment by adizanni** [comment] 2021-08-25 16:16
Hello Christos, yes I'm going to try to manage the groups this can even give some ideas to avoid the # feature (see the README) or the object grouping in the card

**Comment by adizanni** [comment] 2021-09-08 20:55
In absence of a feedback I close the issue. Re-open it if you still experience the issue

**Closed by adizanni** 2021-09-08 20:55 UTC

**Comment by jesserockz** [comment] 2021-09-08 22:04
Working for me recently as I had a small concrete slab level under the house to raise the floor off ground =)

**Comment by Vlastelin40** [comment] 2021-09-09 09:48
It exports everything,but for some reason it does not load into HA

**Comment by Vlastelin40** [comment] 2021-09-09 09:49
Windows 7

**Comment by adizanni** [comment] 2021-09-09 11:42
Hello Vlastelin, you need to give me more info:

console logs
yaml config of the card
obj/mtl file or sh3d file (if needed)

**Comment by Vlastelin40** [comment] 2021-09-09 14:37
Only the mtl file is loaded,the obj file is not loaded(50Mb) file size. HA is installed in VirtualBox.
 
 
 
С уважением,
Владимир Марчуков
***@***.***
 

К этому письму приложены ссылки на следующие файлы:

1. home.obj (58.3 Мб)

Ссылка для скачивания файлов: https://cloud.mail.ru/stock/8QVH87NLSoEem1tGMcypNx8T

Файлы будут храниться до 08.03.2022

**Comment by Vlastelin40** [comment] 2021-09-12 16:09
Good evening.I downloaded the files,now there is another problem.Shows only a gray screen. What could be wrong? All files in the www folder, the paths are spelled out(/hacsfiles/local/home. obj ,/hacsfiles/local/home. mtl ,/hacsfiles/local/home.json)(/hacsfiles/floor3d-card/floor3d-card.js?hacstag=361776538111)
 
С уважением,
Владимир Марчуков
***@***.***

**Comment by adizanni** [comment] 2021-09-12 16:16
The right path for the obj and mtl files is /local/(www folder in config where you have copied the files). No hacsfiles

**Comment by Vlastelin40** [comment] 2021-09-12 17:49
С уважением,
Владимир Марчуков
***@***.***

**Comment by Vlastelin40** [comment] 2021-09-12 21:35
I figured it out, thank you. the path was not correct, I specified /local/ and everything went.
 
С уважением,
Владимир Марчуков
***@***.***

**Comment by Abhome** [comment] 2022-01-11 10:26
> Hello all, I'm back now, in fact my previous post is not correct. The plugin was not working because I was using a previous version. Instead of following my procedure in the readme (I will modify it) please follow these steps in windows:
> 
> 1. Close sweethome3d application
> 2. Download the latest version of the plugin [here](https://github.com/adizanni/ExportToHASS/raw/main/dist/ExportToHassPlugin.sh3p)
> 3. Open the folder located here: "C:\Users\[your user name]\AppData\Roaming\eTeks\Sweet Home 3D\plugins" (replace [your user name] with your actual user name)
> 4. Copy the file downloaded in step 2 to the folder identified in step 3
> 5. Restart sweethome3d,
> 
> In this release I have added a final message box to show that the export was succesful. If you do not see the message box it means you have other problems. But now it will be more difficult for me to debug (until I will put some logs, but this plugin is really developed in best effort). Please try!!!

thank you for your amazing work. I'm not able to get the plugin to work.  can you help?

**Comment by adizanni** [comment] 2022-01-11 14:13
Hello @Abhome do you see the plugin menu at least ? The plugin is very experimental and it works only when all the conditions are met, and still I do not know what are all the conditions :). Can you please tell me:

1. Which Sweethome version are you using
2. I guess it is Windows based
3. Do you see the Export To Hass menu entry in the Tools menu of Sweethome
4. Have you groups or levels in the model you are trying to export
5. Any other info, screenshot you think is relevant.....

**Comment by Abhome** [comment] 2022-01-11 17:33
Thank you for your fast response. I'm using windows, and the sweet home version is  6.4.2. also, I don't have any group. The problem is the plugin won't show up in the menu bar.

**Comment by Abhome** [comment] 2022-01-11 17:47
Just update the sweet home to version 6.6a, and it solves the problem; thank you for your help.

**Comment by Abhome** [comment] 2022-01-11 18:32
Sorry to bother you. My question is, can I bind an entity with the white light source? How can I find the object id of the white light source?

**Comment by adizanni** [comment] 2022-01-11 18:51
The white light source has no effect for the export to home assistant . In SweetHome3D it is used just to do realistic rendering effect. In the floor3d-card you bind directly to the lamp object in order to render the light

**Comment by Abhome** [comment] 2022-01-11 19:01
I'm using a white source light for my led strip. Do you have any solution for the led strip?

**Comment by adizanni** [comment] 2022-01-11 19:17
I have not yet implemented [this type of light](https://threejs.org/docs/#api/en/lights/RectAreaLight) from Three.js. It is not an easy coding. In the mean time I suggest you create a "fake" strip light by putting small objects (ex cubes) in a line in your model and in the card you create an object group that contains all the cubes. After you bind your strip ha light to the object group you will be able to do a stripe like effect. Of course this is consuming a lot of light sources: I remind you that, if you want realistic lights with shadows, the number of lights is limited by the max number of textures that your GPU can handle
